
import os
import json
import sqlite3
import requests
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment
PROJECT_ROOT = Path(__file__).parent.parent
DB_PATH = PROJECT_ROOT / "data" / "backlog" / "backlog.db"
PROJECTS_BASE_DIR = Path("d:/SHARED/Projects")
load_dotenv(PROJECT_ROOT.parent / ".env")

OLLAMA_URL = os.getenv("OLLAMA_API_URL", "http://localhost:11434/api/generate")
MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:14b")

def log(project_id, message, log_type="info"):
    """Log to database and console."""
    print(f"[{log_type.upper()}] Project {project_id}: {message}")
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO agent_logs (project_id, message, log_type) VALUES (?, ?, ?)",
            (project_id, message, log_type)
        )

def get_llm_response(prompt, json_mode=False):
    """Get response from Ollama."""
    try:
        payload = {
            "model": MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.5}
        }
        if json_mode:
            payload["format"] = "json"
            
        r = requests.post(OLLAMA_URL, json=payload, timeout=60)
        r.raise_for_status()
        return r.json()["response"]
    except Exception as e:
        print(f"LLM Error: {e}")
        return None

def create_project(goal):
    """Initialize a new project."""
    
    # 1. Plan structure
    log_msg = f"Analyzing goal: {goal}"
    print(log_msg)
    
    prompt = f"""
    You are a Project Manager Agent.
    Goal: {goal}
    
    1. Suggest a short, snake_case project name.
    2. Suggest a list of sub-folders needed.
    3. Break the goal into 3-5 high-level Backlog Items.
    
    Return JSON only:
    {{
        "project_name": "snake_case_name",
        "folders": ["src", "docs", "tests"],
        "tasks": [
            {{"title": "Task 1", "description": "...", "priority": "P1"}},
            ...
        ]
    }}
    """
    
    response = get_llm_response(prompt, json_mode=True)
    if not response:
        print("Failed to get plan from LLM.")
        return

    try:
        plan = json.loads(response)
    except:
        print("Failed to parse LLM plan.")
        return
        
    project_name = plan["project_name"]
    project_path = PROJECTS_BASE_DIR / project_name
    
    # 2. Create Database Entry
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute(
            "INSERT INTO agent_projects (name, path, goal, status) VALUES (?, ?, ?, 'active')",
            (project_name, str(project_path), goal)
        )
        pid = cursor.lastrowid
        
    log(pid, f"Created project entry: {project_name}")
    
    # 3. Create Folders
    try:
        if not project_path.exists():
            project_path.mkdir(parents=True)
            log(pid, f"Created root folder: {project_path}")
        
        for folder in plan.get("folders", []):
            (project_path / folder).mkdir(exist_ok=True)
            log(pid, f"Created subfolder: {folder}")
            
        # Create a README
        with open(project_path / "README.md", "w") as f:
            f.write(f"# {project_name}\n\nGenerated by Local AI Agent.\n\nGoal: {goal}")
            
    except Exception as e:
        log(pid, f"Filesystem error: {e}", "error")
        
    # 4. Add Tasks to Backlog
    with sqlite3.connect(DB_PATH) as conn:
        for task in plan.get("tasks", []):
            external_id = f"BL-{int(datetime.now().timestamp())}-{task['title'][:3].upper()}"
            conn.execute("""
                INSERT INTO backlog_items (external_id, title, description, category, priority, item_type, status, source_channel)
                VALUES (?, ?, ?, 'AI / Automation', ?, 'work', 'open', 'Project Agent')
            """, (external_id, task['title'], task['description'], task['priority']))
            log(pid, f"Added task: {task['title']}")
            
    log(pid, "Project initialization complete.")
    return pid

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--goal", required=True)
    args = parser.parse_args()
    
    create_project(args.goal)
