#!/usr/bin/env python3
"""
Send notifications to Slack from command line or scripts.

Usage:
    python slack_notify.py "Your message here"
    python slack_notify.py --lead "Security Consultant" --score 85
    python slack_notify.py --digest "AI news summary here"
"""

import argparse
import requests
import json
from datetime import datetime

import os

# Load from environment or .env file
TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
CHANNEL = os.environ.get("SLACK_CHANNEL_LEADS", "")

if not TOKEN:
    # Try loading from .env file
    env_path = os.path.join(os.path.dirname(__file__), "..", "docker", ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                if line.startswith("SLACK_BOT_TOKEN="):
                    TOKEN = line.split("=", 1)[1].strip()
                elif line.startswith("SLACK_CHANNEL_LEADS="):
                    CHANNEL = line.split("=", 1)[1].strip()

HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json"
}

def send_message(text: str, blocks: list = None):
    """Send a message to Slack."""
    payload = {"channel": CHANNEL, "text": text}
    if blocks:
        payload["blocks"] = blocks

    r = requests.post("https://slack.com/api/chat.postMessage",
                      headers=HEADERS, json=payload)
    return r.json().get("ok", False)

def send_lead(title: str, score: int = 0, details: dict = None):
    """Send a lead notification."""
    details = details or {}
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"New Lead (Score: {score})"}
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Role:*\n{title}"},
                {"type": "mrkdwn", "text": f"*Industry:*\n{details.get('industry', 'N/A')}"},
                {"type": "mrkdwn", "text": f"*Location:*\n{details.get('location', 'N/A')}"},
                {"type": "mrkdwn", "text": f"*Duration:*\n{details.get('duration', 'N/A')}"}
            ]
        }
    ]
    if details.get("skills"):
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Skills:* {details['skills']}"}
        })

    return send_message(f"New Lead: {title}", blocks)

def send_digest(content: str, category: str = "AI"):
    """Send a digest notification."""
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"{category} Digest - {datetime.now().strftime('%Y-%m-%d')}"}
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": content}
        },
        {"type": "divider"},
        {
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "Generated by TR Automation Hub"}]
        }
    ]
    return send_message(f"{category} Digest", blocks)

def send_alert(message: str, severity: str = "info"):
    """Send a system alert."""
    emoji = {"info": "ℹ️", "warning": "⚠️", "error": "🚨"}.get(severity, "ℹ️")
    return send_message(f"{emoji} *System Alert*: {message}")

def main():
    parser = argparse.ArgumentParser(description="Send Slack notifications")
    parser.add_argument("message", nargs="?", help="Simple text message")
    parser.add_argument("--lead", help="Send as lead notification (title)")
    parser.add_argument("--score", type=int, default=0, help="Lead relevance score")
    parser.add_argument("--digest", help="Send as digest (content)")
    parser.add_argument("--category", default="AI", help="Digest category")
    parser.add_argument("--alert", help="Send as system alert")
    parser.add_argument("--severity", default="info", choices=["info", "warning", "error"])

    args = parser.parse_args()

    if args.lead:
        ok = send_lead(args.lead, args.score)
    elif args.digest:
        ok = send_digest(args.digest, args.category)
    elif args.alert:
        ok = send_alert(args.alert, args.severity)
    elif args.message:
        ok = send_message(args.message)
    else:
        parser.print_help()
        return

    print("Sent!" if ok else "Failed!")

if __name__ == "__main__":
    main()
